# 워크플로우의 이름 지정
name: CI

# 워크플로우가 시작될 조건 지정
on:
  push:
    branches: [ main ]

jobs:
  build:
    # 실행 환경 지정(Docker)
    runs-on: ubuntu-latest
    # 실행 스텝 지정(Action)
    steps:
      # clone
      - uses: actions/checkout@v3

      # install jdk
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 권한 변경
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # build
      - name: Build with Gradle
        run: ./gradlew clean build